package java

// jdkMethodReturns maps ClassName.methodName → return type for common JDK methods.
// Consulted by resolveChainedReceiver when SymbolTable lookup fails.
//
// Return type conventions:
//   concrete type (e.g. "Stream"): returns that type
//   "SELF": returns receiver type (builder/fluent)
//   "T": returns container's first generic type arg
//   "V": returns Map's value type arg
//   "": terminal operation, chain ends
var jdkMethodReturns = map[string]string{
	// Collection / List / Set
	"List.stream": "Stream", "List.iterator": "Iterator", "List.get": "T",
	"List.set": "T", "List.remove": "T", "List.subList": "List",
	"List.toArray": "Object[]", "List.size": "", "List.isEmpty": "",
	"List.contains": "", "List.add": "", "List.indexOf": "",
	"List.lastIndexOf": "", "List.addAll": "", "List.removeAll": "",
	"List.retainAll": "", "List.clear": "", "List.sort": "",
	"List.containsAll": "", "List.listIterator": "Iterator",
	"List.of": "List", "List.copyOf": "List",
	"Set.stream": "Stream", "Set.iterator": "Iterator", "Set.toArray": "Object[]",
	"Set.size": "", "Set.isEmpty": "", "Set.contains": "",
	"Set.add": "", "Set.remove": "", "Set.addAll": "",
	"Set.clear": "", "Set.of": "Set", "Set.copyOf": "Set",
	"Collection.stream": "Stream", "Collection.iterator": "Iterator", "Collection.toArray": "Object[]",
	"Collection.size": "", "Collection.isEmpty": "", "Collection.contains": "",
	"Collection.add": "", "Collection.remove": "", "Collection.addAll": "",
	"Collection.clear": "", "Collection.removeAll": "",
	"ArrayList.stream": "Stream", "LinkedList.stream": "Stream",

	// Stream
	"Stream.filter": "Stream", "Stream.map": "Stream", "Stream.flatMap": "Stream",
	"Stream.sorted": "Stream", "Stream.distinct": "Stream", "Stream.peek": "Stream",
	"Stream.limit": "Stream", "Stream.skip": "Stream",
	"Stream.mapToInt": "", "Stream.mapToLong": "", "Stream.mapToDouble": "",
	"Stream.of": "Stream", "Stream.empty": "Stream", "Stream.concat": "Stream",
	"Stream.generate": "Stream", "Stream.iterate": "Stream",
	"Stream.collect": "", "Stream.toList": "List", "Stream.forEach": "",
	"Stream.forEachOrdered": "",
	"Stream.findFirst": "Optional", "Stream.findAny": "Optional",
	"Stream.reduce": "Optional", "Stream.min": "Optional", "Stream.max": "Optional",
	"Stream.count": "", "Stream.toArray": "",
	"Stream.anyMatch": "", "Stream.allMatch": "", "Stream.noneMatch": "",

	// Optional
	"Optional.map": "Optional", "Optional.flatMap": "Optional", "Optional.filter": "Optional",
	"Optional.or": "Optional",
	"Optional.orElse": "T", "Optional.orElseGet": "T", "Optional.orElseThrow": "T",
	"Optional.get": "T", "Optional.ifPresent": "", "Optional.isPresent": "",
	"Optional.isEmpty": "",
	"Optional.stream": "Stream",
	"Optional.of": "Optional", "Optional.ofNullable": "Optional", "Optional.empty": "Optional",

	// Map
	"Map.get": "V", "Map.getOrDefault": "V", "Map.put": "V", "Map.remove": "V",
	"Map.entrySet": "Set", "Map.keySet": "Set", "Map.values": "Collection",
	"Map.containsKey": "", "Map.containsValue": "", "Map.size": "", "Map.isEmpty": "",
	"Map.putAll": "", "Map.clear": "", "Map.putIfAbsent": "V",
	"Map.replace": "V", "Map.computeIfAbsent": "V", "Map.computeIfPresent": "V",
	"Map.compute": "V", "Map.merge": "V", "Map.forEach": "",
	"Map.of": "Map", "Map.copyOf": "Map", "Map.entry": "Entry",
	"HashMap.get": "V", "HashMap.put": "V", "HashMap.containsKey": "",
	"LinkedHashMap.get": "V",
	"ConcurrentHashMap.get": "V", "ConcurrentHashMap.put": "V",
	"TreeMap.get": "V", "TreeMap.firstKey": "T", "TreeMap.lastKey": "T",
	"Entry.getKey": "T", "Entry.getValue": "V",

	// Iterator
	"Iterator.next": "T", "Iterator.hasNext": "",

	// Future
	"Future.get": "T", "Future.isDone": "", "Future.cancel": "", "Future.isCancelled": "",
	"CompletableFuture.get": "T", "CompletableFuture.join": "T",
	"CompletableFuture.thenApply": "CompletableFuture",
	"CompletableFuture.thenAccept": "CompletableFuture",
	"CompletableFuture.thenRun": "CompletableFuture",
	"CompletableFuture.thenCompose": "CompletableFuture",
	"CompletableFuture.exceptionally": "CompletableFuture",
	"CompletableFuture.whenComplete": "CompletableFuture",
	"CompletableFuture.handle": "CompletableFuture",
	"CompletableFuture.supplyAsync": "CompletableFuture",
	"CompletableFuture.runAsync": "CompletableFuture",
	"CompletableFuture.allOf": "CompletableFuture",
	"CompletableFuture.anyOf": "CompletableFuture",
	"CompletableFuture.completedFuture": "CompletableFuture",
	"CompletableFuture.isDone": "", "CompletableFuture.complete": "",

	// StringBuilder
	"StringBuilder.append": "SELF", "StringBuilder.insert": "SELF",
	"StringBuilder.reverse": "SELF", "StringBuilder.toString": "String",
	"StringBuilder.delete": "SELF", "StringBuilder.deleteCharAt": "SELF",
	"StringBuilder.replace": "SELF", "StringBuilder.length": "",
	"StringBuilder.charAt": "", "StringBuilder.indexOf": "",
	"StringBuilder.substring": "String", "StringBuilder.capacity": "",
	"StringBuffer.append": "SELF", "StringBuffer.insert": "SELF",
	"StringBuffer.reverse": "SELF", "StringBuffer.toString": "String",
	"StringBuffer.delete": "SELF", "StringBuffer.deleteCharAt": "SELF",
	"StringBuffer.replace": "SELF", "StringBuffer.length": "",
	"StringBuffer.charAt": "", "StringBuffer.indexOf": "",
	"StringBuffer.substring": "String", "StringBuffer.capacity": "",

	// String
	"String.trim": "String", "String.strip": "String",
	"String.stripLeading": "String", "String.stripTrailing": "String",
	"String.toLowerCase": "String", "String.toUpperCase": "String",
	"String.substring": "String", "String.replace": "String",
	"String.replaceAll": "String", "String.replaceFirst": "String",
	"String.valueOf": "String", "String.join": "String",
	"String.format": "String", "String.toString": "String",
	"String.concat": "String", "String.intern": "String",
	"String.repeat": "String",
	"String.chars": "Stream", "String.codePoints": "Stream",
	"String.toCharArray": "",
	"String.getBytes": "",
	"String.length": "", "String.equals": "", "String.equalsIgnoreCase": "",
	"String.contains": "", "String.matches": "",
	"String.startsWith": "", "String.endsWith": "", "String.isEmpty": "",
	"String.isBlank": "", "String.charAt": "", "String.split": "",
	"String.indexOf": "", "String.lastIndexOf": "",
	"String.compareTo": "", "String.compareToIgnoreCase": "",
	"String.hashCode": "", "String.regionMatches": "",

	// Object
	"Object.toString": "String", "Object.getClass": "Class",
	"Object.hashCode": "", "Object.equals": "",
	"Object.clone": "Object", "Object.notify": "", "Object.notifyAll": "",
	"Object.wait": "", "Object.finalize": "",

	// Throwable / Exception
	"Throwable.getMessage":       "String",
	"Throwable.getLocalizedMessage": "String",
	"Throwable.getCause":         "Throwable",
	"Throwable.getStackTrace":    "",
	"Throwable.toString":         "String",
	"Throwable.printStackTrace":  "",
	"Throwable.initCause":        "Throwable",
	"Throwable.getSuppressed":    "",
	"Throwable.addSuppressed":    "",
	"Exception.getMessage":       "String",
	"Exception.getCause":         "Throwable",
	"Exception.getStackTrace":    "",
	"Exception.toString":         "String",
	"RuntimeException.getMessage": "String",
	"RuntimeException.getCause":   "Throwable",
	"RuntimeException.toString":   "String",
	"IOException.getMessage":      "String",
	"IOException.getCause":        "Throwable",
	"SQLException.getMessage":     "String",
	"SQLException.getSQLState":    "String",
	"SQLException.getErrorCode":   "",
	"SQLException.getNextException": "SQLException",
	"Error.getMessage":            "String",
	"Error.getCause":              "Throwable",
	"Error.toString":              "String",

	// Class
	"Class.getName":          "String",
	"Class.getSimpleName":    "String",
	"Class.getCanonicalName": "String",
	"Class.getSuperclass":    "Class",
	"Class.getInterfaces":    "",
	"Class.isInstance":       "",
	"Class.isAssignableFrom": "",
	"Class.newInstance":      "Object",
	"Class.forName":          "Class",
	"Class.cast":             "Object",
	"Class.getMethod":        "",
	"Class.getDeclaredField": "",

	// Number
	"Number.intValue":    "",
	"Number.longValue":   "",
	"Number.floatValue":  "",
	"Number.doubleValue": "",
	"Number.shortValue":  "",
	"Number.byteValue":   "",
	"Integer.parseInt":    "",
	"Integer.valueOf":     "Integer",
	"Integer.intValue":    "",
	"Integer.toString":    "String",
	"Integer.compareTo":   "",
	"Integer.max":         "",
	"Integer.min":         "",
	"Integer.sum":         "",
	"Integer.toHexString": "String",
	"Integer.toBinaryString": "String",
	"Long.parseLong":      "",
	"Long.valueOf":        "Long",
	"Long.longValue":      "",
	"Long.toString":       "String",
	"Long.compareTo":      "",
	"Long.max":            "",
	"Long.min":            "",
	"Long.sum":            "",
	"Double.parseDouble":  "",
	"Double.valueOf":      "Double",
	"Double.toString":     "String",
	"Double.compareTo":    "",
	"Double.isNaN":        "",
	"Double.isInfinite":   "",
	"Float.parseFloat":    "",
	"Float.valueOf":       "Float",
	"Float.toString":      "String",
	"Float.isNaN":         "",
	"Short.parseShort":    "",
	"Short.valueOf":       "Short",
	"Byte.parseByte":      "",
	"Byte.valueOf":        "Byte",
	"Boolean.parseBoolean": "",
	"Boolean.valueOf":     "Boolean",
	"Boolean.booleanValue": "",
	"Boolean.toString":    "String",
	"BigDecimal.add":       "BigDecimal",
	"BigDecimal.subtract":  "BigDecimal",
	"BigDecimal.multiply":  "BigDecimal",
	"BigDecimal.divide":    "BigDecimal",
	"BigDecimal.remainder": "BigDecimal",
	"BigDecimal.pow":       "BigDecimal",
	"BigDecimal.negate":    "BigDecimal",
	"BigDecimal.abs":       "BigDecimal",
	"BigDecimal.max":       "BigDecimal",
	"BigDecimal.min":       "BigDecimal",
	"BigDecimal.compareTo": "",
	"BigDecimal.toString":  "String",
	"BigDecimal.toPlainString": "String",
	"BigDecimal.intValue":  "",
	"BigDecimal.longValue": "",
	"BigDecimal.doubleValue": "",
	"BigDecimal.floatValue": "",
	"BigDecimal.setScale":  "BigDecimal",
	"BigDecimal.stripTrailingZeros": "BigDecimal",
	"BigDecimal.valueOf":   "BigDecimal",
	"BigDecimal.signum":    "",
	"BigDecimal.precision": "",
	"BigDecimal.scale":     "",
	"BigDecimal.unscaledValue": "BigInteger",
	"BigInteger.add":       "BigInteger",
	"BigInteger.subtract":  "BigInteger",
	"BigInteger.multiply":  "BigInteger",
	"BigInteger.divide":    "BigInteger",
	"BigInteger.mod":       "BigInteger",
	"BigInteger.pow":       "BigInteger",
	"BigInteger.negate":    "BigInteger",
	"BigInteger.abs":       "BigInteger",
	"BigInteger.compareTo": "",
	"BigInteger.toString":  "String",
	"BigInteger.intValue":  "",
	"BigInteger.longValue": "",
	"BigInteger.valueOf":   "BigInteger",

	// Enum
	"Enum.name":    "String",
	"Enum.ordinal": "",
	"Enum.valueOf": "SELF",

	// Comparable
	"Comparable.compareTo": "",

	// Iterable
	"Iterable.iterator": "Iterator",
	"Iterable.forEach":  "",

	// Date / Time
	"Date.getTime":   "",
	"Date.setTime":   "",
	"Date.toString":  "String",
	"Date.before":    "",
	"Date.after":     "",
	"Date.compareTo": "",
	"Date.clone":     "Date",
	"Date.from":      "Date",
	"Calendar.getInstance": "Calendar",
	"Calendar.getTime":     "Date",
	"Calendar.setTime":     "",
	"Calendar.get":         "",
	"Calendar.set":         "",
	"Calendar.add":         "",
	"Calendar.getTimeInMillis": "",
	"Calendar.setTimeInMillis": "",
	"Calendar.before":      "",
	"Calendar.after":       "",
	"Calendar.compareTo":   "",
	"Instant.now":          "Instant",
	"Instant.ofEpochMilli": "Instant",
	"Instant.ofEpochSecond": "Instant",
	"Instant.parse":        "Instant",
	"Instant.toEpochMilli": "",
	"Instant.getEpochSecond": "",
	"Instant.plusSeconds":   "Instant",
	"Instant.minusSeconds":  "Instant",
	"Instant.plusMillis":    "Instant",
	"Instant.minusMillis":   "Instant",
	"Instant.isAfter":      "",
	"Instant.isBefore":     "",
	"Instant.atZone":       "ZonedDateTime",
	"Instant.toString":     "String",
	"Instant.compareTo":    "",
	"LocalDate.now":        "LocalDate",
	"LocalDate.of":         "LocalDate",
	"LocalDate.parse":      "LocalDate",
	"LocalDate.from":       "LocalDate",
	"LocalDate.ofEpochDay": "LocalDate",
	"LocalDate.plusDays":    "LocalDate",
	"LocalDate.minusDays":  "LocalDate",
	"LocalDate.plusWeeks":   "LocalDate",
	"LocalDate.minusWeeks":  "LocalDate",
	"LocalDate.plusMonths":  "LocalDate",
	"LocalDate.minusMonths": "LocalDate",
	"LocalDate.plusYears":   "LocalDate",
	"LocalDate.minusYears":  "LocalDate",
	"LocalDate.withDayOfMonth": "LocalDate",
	"LocalDate.withMonth":  "LocalDate",
	"LocalDate.withYear":   "LocalDate",
	"LocalDate.atStartOfDay": "LocalDateTime",
	"LocalDate.atTime":     "LocalDateTime",
	"LocalDate.toEpochDay": "",
	"LocalDate.getYear":    "",
	"LocalDate.getMonthValue": "",
	"LocalDate.getDayOfMonth": "",
	"LocalDate.getDayOfWeek": "DayOfWeek",
	"LocalDate.getDayOfYear": "",
	"LocalDate.lengthOfMonth": "",
	"LocalDate.isAfter":    "",
	"LocalDate.isBefore":   "",
	"LocalDate.isEqual":    "",
	"LocalDate.isLeapYear": "",
	"LocalDate.format":     "String",
	"LocalDate.toString":   "String",
	"LocalDate.compareTo":  "",
	"LocalDate.until":      "Period",
	"LocalDateTime.now":    "LocalDateTime",
	"LocalDateTime.of":     "LocalDateTime",
	"LocalDateTime.parse":  "LocalDateTime",
	"LocalDateTime.from":   "LocalDateTime",
	"LocalDateTime.plusDays":    "LocalDateTime",
	"LocalDateTime.minusDays":  "LocalDateTime",
	"LocalDateTime.plusHours":   "LocalDateTime",
	"LocalDateTime.minusHours":  "LocalDateTime",
	"LocalDateTime.plusMinutes": "LocalDateTime",
	"LocalDateTime.minusMinutes": "LocalDateTime",
	"LocalDateTime.plusSeconds": "LocalDateTime",
	"LocalDateTime.minusSeconds": "LocalDateTime",
	"LocalDateTime.plusWeeks":   "LocalDateTime",
	"LocalDateTime.minusWeeks":  "LocalDateTime",
	"LocalDateTime.plusMonths":  "LocalDateTime",
	"LocalDateTime.minusMonths": "LocalDateTime",
	"LocalDateTime.plusYears":   "LocalDateTime",
	"LocalDateTime.minusYears":  "LocalDateTime",
	"LocalDateTime.withDayOfMonth": "LocalDateTime",
	"LocalDateTime.withHour":   "LocalDateTime",
	"LocalDateTime.withMinute": "LocalDateTime",
	"LocalDateTime.withSecond": "LocalDateTime",
	"LocalDateTime.toLocalDate": "LocalDate",
	"LocalDateTime.toLocalTime": "LocalTime",
	"LocalDateTime.atZone":     "ZonedDateTime",
	"LocalDateTime.getYear":    "",
	"LocalDateTime.getMonthValue": "",
	"LocalDateTime.getDayOfMonth": "",
	"LocalDateTime.getHour":    "",
	"LocalDateTime.getMinute":  "",
	"LocalDateTime.getSecond":  "",
	"LocalDateTime.getDayOfWeek": "DayOfWeek",
	"LocalDateTime.isAfter":    "",
	"LocalDateTime.isBefore":   "",
	"LocalDateTime.isEqual":    "",
	"LocalDateTime.format":     "String",
	"LocalDateTime.toString":   "String",
	"LocalDateTime.compareTo":  "",
	"LocalTime.now":        "LocalTime",
	"LocalTime.of":         "LocalTime",
	"LocalTime.parse":      "LocalTime",
	"LocalTime.plusHours":   "LocalTime",
	"LocalTime.minusHours":  "LocalTime",
	"LocalTime.plusMinutes": "LocalTime",
	"LocalTime.minusMinutes": "LocalTime",
	"LocalTime.getHour":    "",
	"LocalTime.getMinute":  "",
	"LocalTime.getSecond":  "",
	"LocalTime.isAfter":    "",
	"LocalTime.isBefore":   "",
	"LocalTime.format":     "String",
	"LocalTime.toString":   "String",
	"LocalTime.compareTo":  "",
	"ZonedDateTime.now":    "ZonedDateTime",
	"ZonedDateTime.of":     "ZonedDateTime",
	"ZonedDateTime.parse":  "ZonedDateTime",
	"ZonedDateTime.toLocalDate": "LocalDate",
	"ZonedDateTime.toLocalDateTime": "LocalDateTime",
	"ZonedDateTime.toLocalTime": "LocalTime",
	"ZonedDateTime.toInstant": "Instant",
	"ZonedDateTime.getZone": "ZoneId",
	"ZonedDateTime.format":  "String",
	"ZonedDateTime.toString": "String",
	"Duration.ofDays":      "Duration",
	"Duration.ofHours":     "Duration",
	"Duration.ofMinutes":   "Duration",
	"Duration.ofSeconds":   "Duration",
	"Duration.ofMillis":    "Duration",
	"Duration.between":     "Duration",
	"Duration.plus":        "Duration",
	"Duration.minus":       "Duration",
	"Duration.toDays":      "",
	"Duration.toHours":     "",
	"Duration.toMinutes":   "",
	"Duration.toMillis":    "",
	"Duration.getSeconds":  "",
	"Duration.compareTo":   "",
	"Duration.toString":    "String",
	"Period.between":       "Period",
	"Period.ofDays":        "Period",
	"Period.ofMonths":      "Period",
	"Period.ofYears":       "Period",
	"Period.getDays":       "",
	"Period.getMonths":     "",
	"Period.getYears":      "",
	"Period.plus":          "Period",
	"Period.minus":         "Period",
	"Period.toString":      "String",
	"DateTimeFormatter.ofPattern": "DateTimeFormatter",
	"DateTimeFormatter.format":    "String",
	"DateTimeFormatter.parse":     "",
	"System.currentTimeMillis": "",
	"System.nanoTime": "",
	"System.getenv":   "String",
	"System.getProperty": "String",
	"System.setProperty": "String",
	"System.exit":     "",
	"System.gc":       "",
	"System.arraycopy": "",
	"System.lineSeparator": "String",
	"System.identityHashCode": "",

	// Math
	"Math.max":    "",
	"Math.min":    "",
	"Math.abs":    "",
	"Math.round":  "",
	"Math.ceil":   "",
	"Math.floor":  "",
	"Math.random": "",
	"Math.pow":    "",
	"Math.sqrt":   "",
	"Math.log":    "",
	"Math.log10":  "",
	"Math.signum": "",
	"Math.toIntExact": "",
	"Math.addExact":   "",
	"Math.multiplyExact": "",

	// Pattern / Matcher
	"Pattern.compile": "Pattern",
	"Pattern.matcher": "Matcher",
	"Pattern.matches": "",
	"Pattern.quote":   "String",
	"Pattern.split":   "",
	"Matcher.find":    "",
	"Matcher.group":   "String",
	"Matcher.matches": "",
	"Matcher.replaceAll": "String",
	"Matcher.replaceFirst": "String",
	"Matcher.reset":   "Matcher",
	"Matcher.start":   "",
	"Matcher.end":     "",
	"Matcher.groupCount": "",

	// Thread
	"Thread.currentThread": "Thread",
	"Thread.getName":       "String",
	"Thread.getId":         "",
	"Thread.getState":      "",
	"Thread.isAlive":       "",
	"Thread.isInterrupted": "",
	"Thread.sleep":         "",
	"Thread.start":         "",
	"Thread.join":          "",
	"Thread.interrupt":     "",
	"Thread.setName":       "",
	"Thread.setPriority":   "",
	"Thread.setDaemon":     "",

	// UUID
	"UUID.randomUUID": "UUID",
	"UUID.toString":   "String",

	// Arrays / Collections
	"Arrays.asList": "List", "Arrays.stream": "Stream",
	"Arrays.sort": "", "Arrays.copyOf": "", "Arrays.copyOfRange": "",
	"Arrays.fill": "", "Arrays.equals": "", "Arrays.deepEquals": "",
	"Arrays.toString": "String", "Arrays.deepToString": "String",
	"Arrays.binarySearch": "", "Arrays.hashCode": "",
	"Collections.unmodifiableList": "List", "Collections.unmodifiableMap": "Map",
	"Collections.unmodifiableSet": "Set",
	"Collections.singletonList": "List", "Collections.singleton": "Set",
	"Collections.singletonMap": "Map",
	"Collections.emptyList": "List", "Collections.emptyMap": "Map",
	"Collections.emptySet": "Set",
	"Collections.sort": "", "Collections.reverse": "",
	"Collections.shuffle": "", "Collections.swap": "",
	"Collections.frequency": "", "Collections.disjoint": "",
	"Collections.min": "T", "Collections.max": "T",
	"Collections.synchronizedList": "List", "Collections.synchronizedMap": "Map",
	"Collections.synchronizedSet": "Set",
	"Collections.addAll": "",

	// Objects
	"Objects.requireNonNull": "T",
	"Objects.equals": "", "Objects.deepEquals": "",
	"Objects.hash": "", "Objects.hashCode": "",
	"Objects.toString": "String",
	"Objects.isNull": "", "Objects.nonNull": "",

	// Collectors
	"Collectors.toList": "", "Collectors.toSet": "",
	"Collectors.toMap": "", "Collectors.toUnmodifiableList": "",
	"Collectors.joining": "", "Collectors.counting": "",
	"Collectors.groupingBy": "", "Collectors.partitioningBy": "",
	"Collectors.summarizingInt": "", "Collectors.summarizingLong": "",
	"Collectors.toCollection": "",
}

// lookupJDKMethodReturn returns the return type for a JDK method.
// Second return value indicates whether the method was found in the table.
func lookupJDKMethodReturn(className, methodName string) (string, bool) {
	ret, ok := jdkMethodReturns[className+"."+methodName]
	return ret, ok
}

// jdkTypeHierarchy maps className → direct parent types for common JDK classes.
// Used by isJDKSubtype to check type compatibility for overload disambiguation.
var jdkTypeHierarchy = map[string][]string{
	// Throwable hierarchy
	"Throwable":                        {"Object"},
	"Exception":                        {"Throwable"},
	"RuntimeException":                 {"Exception"},
	"Error":                            {"Throwable"},
	"IOException":                      {"Exception"},
	"SQLException":                     {"Exception"},
	"NullPointerException":             {"RuntimeException"},
	"IllegalArgumentException":         {"RuntimeException"},
	"IllegalStateException":            {"RuntimeException"},
	"ClassCastException":               {"RuntimeException"},
	"IndexOutOfBoundsException":        {"RuntimeException"},
	"ArrayIndexOutOfBoundsException":   {"IndexOutOfBoundsException"},
	"StringIndexOutOfBoundsException":  {"IndexOutOfBoundsException"},
	"UnsupportedOperationException":    {"RuntimeException"},
	"ConcurrentModificationException":  {"RuntimeException"},
	"NumberFormatException":            {"IllegalArgumentException"},
	"ArithmeticException":              {"RuntimeException"},
	"SecurityException":                {"RuntimeException"},
	"NoSuchElementException":           {"RuntimeException"},
	"EmptyStackException":              {"RuntimeException"},
	"TypeNotPresentException":          {"RuntimeException"},
	"DateTimeException":                {"RuntimeException"},
	"DateTimeParseException":           {"DateTimeException"},
	"BufferOverflowException":          {"RuntimeException"},
	"BufferUnderflowException":         {"RuntimeException"},
	"CompletionException":              {"RuntimeException"},
	"RejectedExecutionException":       {"RuntimeException"},
	"CancellationException":            {"IllegalStateException"},
	"FileNotFoundException":            {"IOException"},
	"InterruptedException":             {"Exception"},
	"TimeoutException":                 {"Exception"},
	"ExecutionException":               {"Exception"},
	"ClassNotFoundException":           {"Exception"},
	"NoSuchMethodException":            {"Exception"},
	"NoSuchFieldException":             {"Exception"},
	"CloneNotSupportedException":       {"Exception"},
	"ParseException":                   {"Exception"},
	"MalformedURLException":            {"IOException"},
	"SocketException":                  {"IOException"},
	"ConnectException":                 {"SocketException"},
	"SocketTimeoutException":           {"IOException"},
	"EOFException":                     {"IOException"},
	"OutOfMemoryError":                 {"Error"},
	"StackOverflowError":               {"Error"},
	"AssertionError":                   {"Error"},

	// Number hierarchy
	"Number":     {"Object"},
	"Integer":    {"Number"},
	"Long":       {"Number"},
	"Double":     {"Number"},
	"Float":      {"Number"},
	"Short":      {"Number"},
	"Byte":       {"Number"},
	"BigDecimal": {"Number"},
	"BigInteger": {"Number"},

	// String / CharSequence
	"String":        {"CharSequence", "Comparable", "Object"},
	"StringBuilder": {"CharSequence", "Object"},
	"StringBuffer":  {"CharSequence", "Object"},
	"CharSequence":  {"Object"},

	// Collection hierarchy
	"Iterable":   {"Object"},
	"Collection": {"Iterable"},
	"List":       {"Collection"},
	"Set":        {"Collection"},
	"SortedSet":  {"Set"},
	"NavigableSet": {"SortedSet"},
	"Queue":      {"Collection"},
	"Deque":      {"Queue"},
	"ArrayList":  {"List"},
	"LinkedList": {"List", "Deque"},
	"HashSet":    {"Set"},
	"TreeSet":    {"NavigableSet"},
	"LinkedHashSet": {"HashSet"},
	"Vector":     {"List"},
	"Stack":      {"Vector"},
	"PriorityQueue": {"Queue"},
	"ArrayDeque": {"Deque"},
	"CopyOnWriteArrayList": {"List"},

	// Map hierarchy
	"Map":               {"Object"},
	"SortedMap":         {"Map"},
	"NavigableMap":      {"SortedMap"},
	"HashMap":           {"Map"},
	"LinkedHashMap":     {"HashMap"},
	"TreeMap":           {"NavigableMap"},
	"ConcurrentHashMap": {"Map"},
	"Hashtable":         {"Map"},
	"WeakHashMap":       {"Map"},
	"EnumMap":           {"Map"},

	// Boolean / Character / Void
	"Boolean":   {"Comparable", "Object"},
	"Character": {"Comparable", "Object"},
	"Void":      {"Object"},
	"Comparable": {"Object"},

	// Stream / Optional / Future
	"Stream":             {"Object"},
	"Optional":           {"Object"},
	"Future":             {"Object"},
	"CompletableFuture":  {"Future"},

	// Date / Time
	"Date":          {"Comparable", "Object"},
	"Calendar":      {"Comparable", "Object"},
	"Instant":       {"Comparable", "Object"},
	"LocalDate":     {"Comparable", "Object"},
	"LocalDateTime": {"Comparable", "Object"},
	"LocalTime":     {"Comparable", "Object"},
	"ZonedDateTime": {"Object"},
	"Duration":      {"Comparable", "Object"},
	"Period":        {"Object"},
	"DayOfWeek":     {"Enum"},
	"ZoneId":        {"Object"},
	"DateTimeFormatter": {"Object"},

	// IO
	"InputStream":       {"Object"},
	"OutputStream":      {"Object"},
	"Reader":            {"Object"},
	"Writer":            {"Object"},
	"FileInputStream":   {"InputStream"},
	"FileOutputStream":  {"OutputStream"},
	"BufferedReader":     {"Reader"},
	"BufferedWriter":     {"Writer"},
	"InputStreamReader":  {"Reader"},
	"OutputStreamWriter": {"Writer"},
	"PrintWriter":        {"Writer"},
	"PrintStream":        {"OutputStream"},
	"ByteArrayInputStream":  {"InputStream"},
	"ByteArrayOutputStream": {"OutputStream"},
	"StringReader":       {"Reader"},
	"StringWriter":       {"Writer"},
	"File":               {"Comparable", "Object"},
	"Path":               {"Comparable", "Object"},

	// Thread / Runnable
	"Thread":   {"Runnable", "Object"},
	"Runnable": {"Object"},
	"Callable": {"Object"},

	// Enum
	"Enum": {"Comparable", "Object"},

	// Class / Type
	"Class": {"Object"},
	"Type":  {"Object"},

	// Pattern / Matcher
	"Pattern": {"Object"},
	"Matcher": {"Object"},

	// UUID
	"UUID": {"Comparable", "Object"},
}

// isJDKSubtype checks if child is a subtype of parent using the JDK hierarchy table.
func isJDKSubtype(child, parent string) bool {
	if child == parent {
		return true
	}
	ancestors, ok := jdkTypeHierarchy[child]
	if !ok {
		return false
	}
	for _, a := range ancestors {
		if a == parent {
			return true
		}
		if isJDKSubtype(a, parent) {
			return true
		}
	}
	return false
}

// jdkTypeDepth returns the inheritance depth from a type to a target parent.
// Returns -1 if not a subtype. Used to select the most specific overload.
func jdkTypeDepth(child, parent string) int {
	if child == parent {
		return 0
	}
	ancestors, ok := jdkTypeHierarchy[child]
	if !ok {
		return -1
	}
	best := -1
	for _, a := range ancestors {
		if a == parent {
			return 1
		}
		d := jdkTypeDepth(a, parent)
		if d >= 0 && (best < 0 || d+1 < best) {
			best = d + 1
		}
	}
	return best
}
